import { Menu, Search, UserRound, Heart, ShoppingBag, ChevronRight, Check, X } from 'lucide-react'
import { useState } from 'react'
import { BrandLockup } from './components/branding/Brand'
import { Button } from './components/primitives/Button'
import { Badge } from './components/primitives/Badge'
import { Input, QuantitySelector, SearchField, Textarea } from './components/forms/Fields'
import { ProductGrid, type Product } from './components/ecommerce/ProductCard'
import { Hero, Newsletter, OrderRequestBanner, WhatsAppCTA } from './components/marketing/Marketing'

const products: Product[] = [
  { image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=85', brand: 'COACH', name: 'Tabby Shoulder Bag 26', price: '$6,850', badge: 'featured' },
  { image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=85', brand: 'NEW BALANCE', name: 'Zapatillas 327', price: '$2,990', compareAt: '$3,490', badge: 'sale' },
  { image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=85', brand: 'MARC JACOBS', name: 'Perfect Eau de Parfum', price: '$2,180', badge: 'new' },
  { image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=800&q=85', brand: 'RAY-BAN', name: 'Lentes de sol clásicos', price: '$3,250', badge: 'order' },
]
function Header() { const [open, setOpen] = useState(false); return <><div className="announcement">Envíos nacionales · Piezas auténticas · Atención personalizada</div><header><button className="mobile-only icon-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Abrir navegación"><Menu size={20}/></button><BrandLockup compact/><nav className={open ? 'open' : ''} aria-label="Navegación principal"><a href="#coleccion">Moda</a><a href="#coleccion">Accesorios</a><a href="#pedido">Sobre pedido</a><a href="#historia">Nuestra historia</a></nav><div className="header-actions"><button className="desktop-only icon-button" aria-label="Buscar"><Search size={19}/></button><button className="desktop-only icon-button" aria-label="Cuenta"><UserRound size={19}/></button><button className="icon-button" aria-label="Favoritos"><Heart size={19}/></button><button className="icon-button cart-button" aria-label="Bolsa"><ShoppingBag size={19}/><span>2</span></button></div></header></> }
function Foundations() { return <section className="section" id="fundamentos"><div className="section-heading"><p className="eyebrow">01 / FOUNDATIONS</p><h2>Una base pensada<br/><em>para perdurar.</em></h2><p>Tokens semánticos que mantienen la identidad consistente en cada interacción.</p></div><div className="foundation-grid"><article><h3>Color</h3><div className="swatches">{[['Marfil','ivory'],['Champagne','champagne'],['Nude','nude'],['Dorado','gold'],['Negro','black'],['Rose gold','rose']].map(([name, tone])=><div key={tone}><span className={`swatch ${tone}`}/><small>{name}</small></div>)}</div></article><article><h3>Tipografía</h3><p className="type-display">V&E Fashion-Beauty</p><p className="type-sans">Inter — interfaz clara y cálida</p><p className="type-caption">DISPLAY / SANS-SERIF / 01</p></article><article><h3>Escala</h3><div className="spacing-scale">{[4,8,16,24,32,48].map((n)=><div key={n}><i style={{width:n}}/><small>{n}px</small></div>)}</div><div className="radius-row"><span>2px</span><span>4px</span><span>8px</span><span>12px</span></div></article></div></section> }
function Components() { return <section className="section components-section" id="componentes"><div className="section-heading"><p className="eyebrow">02 / PRIMITIVES</p><h2>Detalles que hacen<br/><em>sentir cuidado.</em></h2></div><div className="component-board"><article><h3>Acciones</h3><div className="button-row"><Button>Primario</Button><Button variant="secondary">Secundario</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="accent">Accent</Button><Button variant="destructive">Eliminar</Button></div><div className="button-row"><Button loading>Cargando</Button><Button disabled>Deshabilitado</Button></div></article><article><h3>Etiquetas</h3><div className="badge-row"><Badge kind="new"/><Badge kind="sale"/><Badge kind="featured"/><Badge kind="limited"/><Badge kind="order"/><Badge kind="out"/></div><h3 className="mini-heading">Feedback</h3><div className="alert"><Check size={17}/> Tu selección se agregó a la bolsa.</div><div className="alert error"><X size={17}/> Revisa los datos antes de continuar.</div></article><article><h3>Campos</h3><SearchField/><Input label="Nombre completo" placeholder="Elizabeth V."/><Textarea label="Nota para tu pedido" placeholder="¿Cómo podemos ayudarte?" rows={2}/><div className="field"><label>Cantidad</label><QuantitySelector/></div></article></div></section> }
function ProductDetail() { return <section className="product-detail" id="coleccion"><div className="detail-images"><img src={products[0].image} alt="Bolsa beige Coach"/><img src="https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=85" alt="Detalle de bolsa de piel"/></div><div className="detail-info"><p className="eyebrow">COLECCIÓN DESTACADA</p><h2>Una selección que habla de <em>ti.</em></h2><p>Diseños icónicos, belleza cotidiana y accesorios que se convierten en parte de tu historia.</p><a href="#catalogo" className="text-link">Ver todas las novedades <ChevronRight size={16}/></a></div></section> }
function App() { return <><Header/><main><Hero/><Foundations/><Components/><ProductDetail/><section className="section" id="catalogo"><div className="catalog-head"><div><p className="eyebrow">03 / ECOMMERCE</p><h2>Piezas con <em>presencia.</em></h2></div><Button variant="outline">Ver catálogo</Button></div><ProductGrid products={products}/></section><div id="pedido"><OrderRequestBanner/></div><section className="section category-section"><div className="section-heading"><p className="eyebrow">04 / CATEGORÍAS</p><h2>Todo lo que<br/><em>te representa.</em></h2></div><div className="category-grid">{['Moda','Accesorios','Bolsas','Calzado','Bisutería','Belleza','Perfumes','Cuidado personal'].map((name, index)=><a href="#catalogo" key={name}><span>0{index + 1}</span>{name}<ChevronRight size={17}/></a>)}</div></section><Newsletter/></main><footer id="historia"><BrandLockup/><p>Elegancia · Estilo · Belleza</p><small>© {new Date().getFullYear()} V&E Fashion-Beauty. UI kit de referencia.</small></footer><WhatsAppCTA/></> }
export { App }
